apiVersion: v1
kind: Service
metadata:
  name: whatsapp-backend-service
spec:
  selector:
    app: whatsapp-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000  
  type: LoadBalancer # Change service type as needed (NodePort, ClusterIP, LoadBalancer)
