apiVersion: v1
kind: Service
metadata:
  name: whatsapp-frontend-service
spec:
  selector:
    app: whatsapp-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000 # Replace with the port your React app listens on
  type: LoadBalancer # Change service type as needed (NodePort, ClusterIP, LoadBalancer)
